[project]
name = "aoc2025"
version = "0.1.0"
description = "AoC 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pillow>=12.0.0",
    "pulp>=3.3.0",
    "scipy>=1.16.3",
    "tqdm>=4.67.1",
]
